/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminCatalogueProductIndexRouteImport } from './routes/_authenticated/admin/catalogue/product/index'
import { Route as AuthenticatedAdminCatalogueProductCreateIndexRouteImport } from './routes/_authenticated/admin/catalogue/product/create/index'
import { Route as AuthenticatedAdminCatalogueProductUpdateProductIdIndexRouteImport } from './routes/_authenticated/admin/catalogue/product/update/$productId/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCatalogueProductIndexRoute =
  AuthenticatedAdminCatalogueProductIndexRouteImport.update({
    id: '/catalogue/product/',
    path: '/catalogue/product/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCatalogueProductCreateIndexRoute =
  AuthenticatedAdminCatalogueProductCreateIndexRouteImport.update({
    id: '/catalogue/product/create/',
    path: '/catalogue/product/create/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCatalogueProductUpdateProductIdIndexRoute =
  AuthenticatedAdminCatalogueProductUpdateProductIdIndexRouteImport.update({
    id: '/catalogue/product/update/$productId/',
    path: '/catalogue/product/update/$productId/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/products/': typeof ProductsIndexRoute
  '/admin/catalogue/product/': typeof AuthenticatedAdminCatalogueProductIndexRoute
  '/admin/catalogue/product/create/': typeof AuthenticatedAdminCatalogueProductCreateIndexRoute
  '/admin/catalogue/product/update/$productId/': typeof AuthenticatedAdminCatalogueProductUpdateProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/products': typeof ProductsIndexRoute
  '/admin/catalogue/product': typeof AuthenticatedAdminCatalogueProductIndexRoute
  '/admin/catalogue/product/create': typeof AuthenticatedAdminCatalogueProductCreateIndexRoute
  '/admin/catalogue/product/update/$productId': typeof AuthenticatedAdminCatalogueProductUpdateProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/admin/catalogue/product/': typeof AuthenticatedAdminCatalogueProductIndexRoute
  '/_authenticated/admin/catalogue/product/create/': typeof AuthenticatedAdminCatalogueProductCreateIndexRoute
  '/_authenticated/admin/catalogue/product/update/$productId/': typeof AuthenticatedAdminCatalogueProductUpdateProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/products/'
    | '/admin/catalogue/product/'
    | '/admin/catalogue/product/create/'
    | '/admin/catalogue/product/update/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/products'
    | '/admin/catalogue/product'
    | '/admin/catalogue/product/create'
    | '/admin/catalogue/product/update/$productId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/products/'
    | '/_authenticated/admin/catalogue/product/'
    | '/_authenticated/admin/catalogue/product/create/'
    | '/_authenticated/admin/catalogue/product/update/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/catalogue/product/': {
      id: '/_authenticated/admin/catalogue/product/'
      path: '/catalogue/product'
      fullPath: '/admin/catalogue/product/'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueProductIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/catalogue/product/create/': {
      id: '/_authenticated/admin/catalogue/product/create/'
      path: '/catalogue/product/create'
      fullPath: '/admin/catalogue/product/create/'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueProductCreateIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/catalogue/product/update/$productId/': {
      id: '/_authenticated/admin/catalogue/product/update/$productId/'
      path: '/catalogue/product/update/$productId'
      fullPath: '/admin/catalogue/product/update/$productId/'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueProductUpdateProductIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCatalogueProductIndexRoute: typeof AuthenticatedAdminCatalogueProductIndexRoute
  AuthenticatedAdminCatalogueProductCreateIndexRoute: typeof AuthenticatedAdminCatalogueProductCreateIndexRoute
  AuthenticatedAdminCatalogueProductUpdateProductIdIndexRoute: typeof AuthenticatedAdminCatalogueProductUpdateProductIdIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCatalogueProductIndexRoute:
      AuthenticatedAdminCatalogueProductIndexRoute,
    AuthenticatedAdminCatalogueProductCreateIndexRoute:
      AuthenticatedAdminCatalogueProductCreateIndexRoute,
    AuthenticatedAdminCatalogueProductUpdateProductIdIndexRoute:
      AuthenticatedAdminCatalogueProductUpdateProductIdIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
