/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminProductIndexRouteImport } from './routes/_authenticated/admin/product/index'
import { Route as AuthenticatedAdminProductDetailsProductIdRouteImport } from './routes/_authenticated/admin/product/details.$productId'
import { Route as AuthenticatedAdminProductUpdateProductIdIndexRouteImport } from './routes/_authenticated/admin/product/update/$productId/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminProductIndexRoute =
  AuthenticatedAdminProductIndexRouteImport.update({
    id: '/product/',
    path: '/product/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductDetailsProductIdRoute =
  AuthenticatedAdminProductDetailsProductIdRouteImport.update({
    id: '/product/details/$productId',
    path: '/product/details/$productId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProductUpdateProductIdIndexRoute =
  AuthenticatedAdminProductUpdateProductIdIndexRouteImport.update({
    id: '/product/update/$productId/',
    path: '/product/update/$productId/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/products/': typeof ProductsIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/product/': typeof AuthenticatedAdminProductIndexRoute
  '/admin/product/details/$productId': typeof AuthenticatedAdminProductDetailsProductIdRoute
  '/admin/product/update/$productId/': typeof AuthenticatedAdminProductUpdateProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/product': typeof AuthenticatedAdminProductIndexRoute
  '/admin/product/details/$productId': typeof AuthenticatedAdminProductDetailsProductIdRoute
  '/admin/product/update/$productId': typeof AuthenticatedAdminProductUpdateProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/product/': typeof AuthenticatedAdminProductIndexRoute
  '/_authenticated/admin/product/details/$productId': typeof AuthenticatedAdminProductDetailsProductIdRoute
  '/_authenticated/admin/product/update/$productId/': typeof AuthenticatedAdminProductUpdateProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/products/'
    | '/admin/'
    | '/admin/product/'
    | '/admin/product/details/$productId'
    | '/admin/product/update/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products'
    | '/admin'
    | '/admin/product'
    | '/admin/product/details/$productId'
    | '/admin/product/update/$productId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/products/'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/product/'
    | '/_authenticated/admin/product/details/$productId'
    | '/_authenticated/admin/product/update/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/product/': {
      id: '/_authenticated/admin/product/'
      path: '/product'
      fullPath: '/admin/product/'
      preLoaderRoute: typeof AuthenticatedAdminProductIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/product/details/$productId': {
      id: '/_authenticated/admin/product/details/$productId'
      path: '/product/details/$productId'
      fullPath: '/admin/product/details/$productId'
      preLoaderRoute: typeof AuthenticatedAdminProductDetailsProductIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/product/update/$productId/': {
      id: '/_authenticated/admin/product/update/$productId/'
      path: '/product/update/$productId'
      fullPath: '/admin/product/update/$productId/'
      preLoaderRoute: typeof AuthenticatedAdminProductUpdateProductIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminProductIndexRoute: typeof AuthenticatedAdminProductIndexRoute
  AuthenticatedAdminProductDetailsProductIdRoute: typeof AuthenticatedAdminProductDetailsProductIdRoute
  AuthenticatedAdminProductUpdateProductIdIndexRoute: typeof AuthenticatedAdminProductUpdateProductIdIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminProductIndexRoute: AuthenticatedAdminProductIndexRoute,
    AuthenticatedAdminProductDetailsProductIdRoute:
      AuthenticatedAdminProductDetailsProductIdRoute,
    AuthenticatedAdminProductUpdateProductIdIndexRoute:
      AuthenticatedAdminProductUpdateProductIdIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
